services:
  - type: web
    name: mediconnect-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mediconnect-db
          property: connectionString
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: CORS_ORIGINS
        value: "https://frontend-rosy-seven-40.vercel.app"
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: mediconnect-db
    plan: free
    databaseName: mediconnect
    user: mediconnect_user
